#!/usr/bin/env bash
# =============================================================================
# Borderland @ GCEE — one-shot setup for a fresh Google Compute Engine VM
# (Debian 12 / Ubuntu 22.04+). Safe to re-run: it upgrades Docker, keeps the
# existing .env, rebuilds the image and restarts the stack.
#
#   1. Create the VM in the Google Cloud console (e2-small is plenty),
#      tick "Allow HTTP traffic" and "Allow HTTPS traffic".
#   2. Copy this project onto the VM (git clone, or scp the folder).
#   3. On the VM:
#          cd <project folder>
#          sudo bash deploy/setup-gcp-vm.sh
#
# Options (environment variables):
#   DOMAIN=game.example.com   hostname pointing at the VM -> automatic HTTPS.
#                             Omit for plain HTTP on the VM's external IP.
#   ADMIN_PASSWORD=...        SUPER_ADMIN password (default: generated).
#   ADMIN_USERNAME=...        default "admin".
#
# Example:  sudo DOMAIN=game.example.com bash deploy/setup-gcp-vm.sh
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------- helpers
c_bold=$'\e[1m'; c_green=$'\e[32m'; c_yellow=$'\e[33m'; c_red=$'\e[31m'; c_off=$'\e[0m'
say()  { printf '%s==>%s %s\n' "$c_green" "$c_off" "$*"; }
warn() { printf '%s!!%s  %s\n' "$c_yellow" "$c_off" "$*"; }
die()  { printf '%sERROR:%s %s\n' "$c_red" "$c_off" "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run with sudo: sudo bash deploy/setup-gcp-vm.sh"
command -v apt-get >/dev/null || die "This script expects a Debian/Ubuntu VM (apt-get not found)."

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"
[[ -f docker-compose.prod.yml ]] || die "docker-compose.prod.yml not found in $PROJECT_DIR"

# The user who invoked sudo owns the checkout and gets docker access.
RUN_USER="${SUDO_USER:-root}"
COMPOSE=(docker compose -f docker-compose.prod.yml)

# ---------------------------------------------------------------- 1. system
say "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl gnupg git openssl chrony cron >/dev/null

# Accurate time on the server matters: every phone syncs its clock to it so
# sub-rounds start simultaneously. GCE images ship chrony pointed at Google's
# NTP; make sure it is running.
systemctl enable --now chrony >/dev/null 2>&1 || true
timedatectl set-ntp true >/dev/null 2>&1 || true

# ---------------------------------------------------------------- 2. docker
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker Engine + Compose plugin"
  curl -fsSL https://get.docker.com | sh >/dev/null
else
  say "Docker already installed: $(docker --version)"
fi
systemctl enable --now docker >/dev/null
docker compose version >/dev/null 2>&1 || die "Docker Compose plugin missing. Install docker-compose-plugin and re-run."
if [[ "$RUN_USER" != "root" ]] && ! id -nG "$RUN_USER" | grep -qw docker; then
  usermod -aG docker "$RUN_USER"
  warn "Added $RUN_USER to the docker group (takes effect on next login)."
fi

# ---------------------------------------------------------------- 3. .env
EXTERNAL_IP="$(curl -s -m 3 -H 'Metadata-Flavor: Google' \
  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip 2>/dev/null || true)"
[[ -n "$EXTERNAL_IP" ]] || EXTERNAL_IP="$(curl -s -m 3 https://api.ipify.org 2>/dev/null || echo '<VM-EXTERNAL-IP>')"

if [[ -f .env ]]; then
  say "Keeping existing .env"
  if [[ -n "${DOMAIN:-}" ]]; then
    sed -i "s|^SITE_ADDRESS=.*|SITE_ADDRESS=${DOMAIN}|" .env
    say "SITE_ADDRESS updated to ${DOMAIN}"
  fi
else
  say "Writing .env with generated secrets"
  ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
  ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | cut -c1-14)}"
  SITE_ADDRESS="${DOMAIN:-:80}"
  CPUS="$(nproc 2>/dev/null || echo 2)"
  WORKERS=$(( CPUS * 2 + 1 )); (( WORKERS > 8 )) && WORKERS=8
  umask 077
  cat > .env <<EOF
# Generated by deploy/setup-gcp-vm.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep private.
SITE_ADDRESS=${SITE_ADDRESS}
JWT_SECRET=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 16)
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
WEB_CONCURRENCY=${WORKERS}
CORS_ORIGINS=*
ENVIRONMENT=production
EOF
  chown "$RUN_USER":"$RUN_USER" .env 2>/dev/null || true
fi
chmod 600 .env

# shellcheck disable=SC1091
set -a; source .env; set +a

# ---------------------------------------------------------------- 4. stack
say "Building the image and starting the stack (first build takes a few minutes)"
"${COMPOSE[@]}" pull --quiet caddy postgres redis 2>/dev/null || true
"${COMPOSE[@]}" up -d --build --remove-orphans

say "Waiting for the API to come up"
for i in $(seq 1 60); do
  if curl -sf -m 3 http://127.0.0.1/api/v1/health >/dev/null 2>&1; then
    printf '    healthy after ~%ss\n' $(( i * 3 ))
    break
  fi
  if (( i == 60 )); then
    warn "API not healthy yet. Check: docker compose -f docker-compose.prod.yml logs api"
  fi
  sleep 3
done

# ---------------------------------------------------------------- 5. backups
say "Installing the daily database backup (03:15, keeps 14 days) -> $PROJECT_DIR/backups"
chmod +x deploy/backup-db.sh
mkdir -p backups
cat > /etc/cron.d/borderland-backup <<EOF
15 3 * * * root cd $PROJECT_DIR && ./deploy/backup-db.sh >> backups/backup.log 2>&1
EOF
chmod 644 /etc/cron.d/borderland-backup

# ---------------------------------------------------------------- 6. summary
if [[ "$SITE_ADDRESS" == ":80" ]]; then
  BASE_URL="http://${EXTERNAL_IP}"
  HTTPS_NOTE="${c_bold}HTTPS${c_off}: you are on plain HTTP. For HTTPS point a hostname at ${EXTERNAL_IP}
(a free DuckDNS name works) and re-run:
  sudo DOMAIN=your-name.duckdns.org bash deploy/setup-gcp-vm.sh
"
else
  BASE_URL="https://${SITE_ADDRESS}"
  HTTPS_NOTE="${c_bold}HTTPS${c_off}: Caddy obtains and renews the certificate for ${SITE_ADDRESS} automatically
(the hostname must already resolve to ${EXTERNAL_IP} and ports 80/443 must be open).
"
fi

cat <<EOF

${c_bold}${c_green}Borderland @ GCEE is up.${c_off}

  Team app    ${BASE_URL}/team-app/
  Admin app   ${BASE_URL}/admin-app/
  Admin login ${ADMIN_USERNAME}  /  password is ADMIN_PASSWORD in ${PROJECT_DIR}/.env

${c_bold}Firewall${c_off} (done once, from your own machine or Cloud Shell — NOT needed if you
ticked "Allow HTTP/HTTPS traffic" when creating the VM):
  gcloud compute firewall-rules create allow-web --allow tcp:80,tcp:443 --target-tags http-server,https-server
  gcloud compute instances add-tags $(hostname) --tags http-server,https-server --zone <ZONE>

${HTTPS_NOTE}
${c_bold}Everyday commands${c_off} (run in ${PROJECT_DIR}):
  docker compose -f docker-compose.prod.yml ps                # status
  docker compose -f docker-compose.prod.yml logs -f api       # live API log
  docker compose -f docker-compose.prod.yml restart           # restart everything
  git pull && sudo bash deploy/setup-gcp-vm.sh                # deploy an update
  ./deploy/backup-db.sh                                       # backup now

EOF
